### ISSUE TITLE
Build failure: missing Properties/Resources.resx

### ISSUE THREAD

**Issue by SamB** [Dijji/RepairTasks#12] opened 2017-12-18 02:11 UTC
So, when I try to build this in VS 2013 or 2015, I get an error along the lines of:

> <tt>C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(2584,5): error MSB3552: Resource file "Properties\Resources.resx" cannot be found.</tt>

There's also some sort of complaint about System.Xaml not being found (apparently it doesn't actually exist until .NET 4.0), but that seems to just be a warning.

**Comment by Dijji** [comment] 2018-01-13 20:16
I have added the missing resource files. Thank you for letting me know about this. Sorry response was slow, I was expecting to be notified when an issue was created.

**Comment by Dijji** [comment] 2018-01-14 11:48
Can you please check that the problem is now fixed?

**Comment by Dijji** [comment] 2018-03-24 18:48
Fixed

**Closed by Dijji** 2018-03-24 18:48 UTC
